mode: standalone

rootUser: minio
rootPassword: minio123

persistence:
  enabled: False

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m

service:
  type: ClusterIP